name: Build, Test, and Deploy the Function App

on:
  push:
    branches:
      - develop
      - staging
      - master

  pull_request:
    branches:
      - develop

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: build-deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  AZURE_WEBAPP_NAME: app-net8-dev
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_FUNCTION_APP_PACKAGE_FOLDER: function-app-package # --------------------------------------------------- the folder in which to store the function app package
  BUILD_CONFIGURATION: Release # ------------------------------------------------------------------------------ the build configuration to use
  DOTNET_VERSION: 8.0.x # ------------------------------------------------------------------------------------- the .net version to use
  PUBLISH_ARTIFACT_NAME: published-function-app
  PUBLISH_PROJECT_FOLDER: src/Kgm.ExampleNetEight.FunctionApp # ----------------------------------------------- the path to the folder that contains the project
  PUBLISH_OUTPUT_FOLDER: published-output # ------------------------------------------------------------------- the folder in which to store the publish output
  PUBLISH_PROJECT_PATH: ./src/Kgm.ExampleNetEight.FunctionApp/Kgm.ExampleNetEight.FunctionApp.csproj # -------- the path to the project to publish
  SOLUTION_PATH: ./Kgm.ExampleNetEight.FunctionApp.sln # ------------------------------------------------------ the path to the solution *.sln file
  TEST_RESULTS_FOLDER: test-results # ------------------------------------------------------------------------- the folder in which to store the test results
  TEST_COVERAGE_SETTINGS_FILE_PATH: ./test/unit-tests/coverlet.runsettings # ---------------------------------- the path to the code coverage settings file

jobs:
  build-and-test:
    name: Build and test the Function App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          popd

      - name: Build
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
          popd

      - name: List Files after build
        run: |
          ls

      - name: Test
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --results-directory ${{ env.TEST_RESULTS_FOLDER }} --logger trx --logger console --collect:"XPlat Code Coverage"
          popd

      - name: List Files after Test
        run: |
          ls
          ls ${{ env.TEST_RESULTS_FOLDER }}

      - name: Publish Function App
        shell: bash
        run: |
          pushd './${{ env.PUBLISH_PROJECT_FOLDER }}'
          dotnet publish --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --output ./${{ env.PUBLISH_OUTPUT_FOLDER }}
          popd

      - name: List published files
        shell: bash
        run: |
          ls ./${{ env.PUBLISH_PROJECT_FOLDER }}/${{ env.PUBLISH_OUTPUT_FOLDER}}

  #     - name: List published files
  #       run: |
  #           ls ${{ env.PUBLISH_OUTPUT_FOLDER }}
      
  #     - name: Archive published function app
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ${{ env.PUBLISH_ARTIFACT_NAME }}
  #         path: ${{ env.PUBLISH_OUTPUT_FOLDER }}
  #         if-no-files-found: error

  # #     - name: Directory listing
  # #       run: ls

  # deploy:
  #   name: Deploy the Function App to the environment
  #   if: ${{ github.event_name == 'push' }}
  #   runs-on: windows-latest
  #   needs: build-and-test
  #   environment: ${{ github.ref_name == 'master' && 'production' || github.ref_name == 'staging' && 'stage' || 'development' }}
  #   steps:
  #     - name: Download the published function app
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: ${{ env.PUBLISH_ARTIFACT_NAME }}
  #         path: ${{ env.AZURE_FUNCTION_APP_PACKAGE_FOLDER }}

  #     # - name: List files after download
  #       # run: ls ${{ env.AZURE_FUNCTION_APP_PACKAGE_FOLDER }}
  #     # - name: List files after download
  #       # run: ls ${{ env.AZURE_FUNCTION_APP_PACKAGE_FOLDER }}/runtimes
  #     # - name: List files after download
  #       # run: ls ${{ env.AZURE_FUNCTION_APP_PACKAGE_FOLDER }}/runtimes/win
  #     # - name: List files after download
  #       # run: ls ${{ env.AZURE_FUNCTION_APP_PACKAGE_FOLDER }}/runtimes/win/lib
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 'ffa0e881-27c8-41f6-9ccd-7d632847a53d'
          tenant-id: '833a9480-bdcd-4d3d-9f4e-d0a7d9814209'
          subscription-id: '92c40ca0-a6b2-4b4d-a328-6d63fc4533ee'
          # creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure Functions Action
        uses: azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PUBLISH_PROJECT_FOLDER}}/${{ env.PUBLISH_OUTPUT_FOLDER }}

  #     - name: Deploy to Azure Function App
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
  #         package: ${{ env.AZURE_FUNCTION_APP_PACKAGE_FOLDER }}

  #     # - name: Log out of Azure
  #     #   run: az logout
